title: Antoine Viscardi
name: Antoine Viscardi
markdown: kramdown

collections_dir: collections

plugins:
  - jemoji

collections:
  insights:
    output: true
    permalink: /:collection/:title

defaults:
  -
    scope:
      path: ""
      type: books
    values:
      layout: book
  -
    scope:
      path: ""
      type: insights
    values:
      layout: post