title: Antoine Viscardi
name: Antoine Viscardi
markdown: kramdown

collections_dir: collections

plugins:
  - jemoji

collections:

  books:
    output: true

  books_current:
    permalink: /books/:path
    output: true

  projects:
    output: true

  projects_current:
    permalink: /projects/:path
    output: true

  blogs:
    output: true

  journals:
    output: true

defaults:
  -
    scope:
      path: ""
      type: books
    values:
      layout: book
  -
    scope:
      path: ""
      type: books_current
    values:
      layout: book
  -
    scope:
      path: ""
      type: projects
    values:
      layout: post
  -
    scope:
      path: ""
      type: projects_current
    values:
      layout: post
  -
    scope:
      path: ""
      type: blogs
    values:
      layout: post
  -
    scope:
      path: ""
      type: journals
    values:
      layout: post